spring.application.name=photoz

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Azure SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://test-ai-server.database.windows.net:1433;database=photoz-app-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=${AZURE_SQL_USERNAME}
spring.datasource.password=${AZURE_SQL_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# JPA Configuration for Azure SQL
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.initialization-fail-timeout=120000
spring.datasource.hikari.connection-timeout=90000
spring.datasource.hikari.idle-timeout=700000
spring.datasource.hikari.max-lifetime=1200000


# Disable schema initialization for tests
spring.test.database.replace=none